name: second Job

on: push

jobs:
    first_job:
      runs-on: ubuntu-latest
      steps:
      - name: checkout repo
        uses: actions/checkout@v5

      - name: fist job
        run: ./test.sh

    #   - name: List the file
    #     run: ls

    #   - name: Cat the file
    #     run: cat README.md
        